name: Build Android Phi Recorder

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


env:
  CARGO_TERM_COLOR: always
  ANDROID_HOME: ${{github.workspace}}/android-sdk
  ANDROID_NDK_HOME: ${{github.workspace}}/android-ndk-r27c
  ANDROID_NDK_ROOT: ${{github.workspace}}/android-ndk-r27c

jobs:
  Build-For-Android:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4.2.2
    
    - run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libasound2-dev libssl-dev pkg-config
        
    - name: Download static-lib
      uses: suisei-cn/actions-download-file@v1.3.0
      id: downlod-static-lib
      with:
        url: "https://teamflos.github.io/phira-docs/phira_build_guide/prpr-avc.zip"
        target: ./

    - name: Set Up static-lib
      run: |
        unzip -o prpr-avc.zip -d ./
    - name: Install Android SDK Tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip -d $ANDROID_HOME
        echo y | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools" "build-tools;33.0.2" "platforms;android-35"
    - name: Install Android NDK
      run: |
        wget https://googledownloads.cn/android/repository/android-ndk-r27c-linux.zip
        unzip android-ndk-r27c-linux.zip -d ${{github.workspace}}
    - name: Install Rust Toolchains
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        target: aarch64-linux-android
    
    - name: Build for Android , arm-v8a
      run: |
        cd phire-ui
        cargo install cargo-ndk
        cargo ndk -t arm64-v8a -p 35 build --release
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-build-aarch64
        path: |
          target/aarch64-linux-android/release/libphire.so
          target/aarch64-linux-android/release/libphireui.so
          target/aarch64-linux-android/release/libphire_ui.so
          target/aarch64-linux-android/release/libmain.so
    - name: Build for Android , armeabi-v7a
      run: |
        cd phire-ui
        rustup target install armv7-linux-androideabi
        cargo install cargo-ndk
        cargo ndk -t armeabi-v7a -p 35 build --release
        ls
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-build-armeabi
        path: |
          target/armv7-linux-androideabi/release/libphire_ui.so
          target/armv7-linux-androideabi/release/libphireui.so
          target/armv7-linux-androideabi/release/libphire.so
          target/armv7-linux-androideabi/release/libmain.so
          
